# .golangci.yml
run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    # - copyloopvar
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    # - typecheck  # explicitly excluded by not enabling
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
  exclude-rules:
    # Exclude issues related to "simtypes"
    - linters:
        - staticcheck
      text: "simtypes"

    # Exclude weak RNG warning from gosec
    - linters:
        - gosec
      text: "Use of weak random number generator"

    # ST1003: Poorly named variable (allowed for now)
    - linters:
        - stylecheck
      text: "ST1003:"

    # ST1016: Receiver name should be a reflection of its identity
    # FIXME: Disabled until golangci-lint updates stylecheck
    # https://github.com/dominikh/go-tools/issues/389
    - linters:
        - stylecheck
      text: "ST1016:"

    # SA1019: Use of deprecated function
    - linters:
        - staticcheck
      text: "SA1019:"
      path: migrations

linters-settings:
  revive:
    # Ignore GENERATED files
    ignore-generated-header: true

  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - blank
      - dot
      - prefix(github.com/cometbft/cometbft)
      - prefix(github.com/cosmos)
      - prefix(cosmossdk.io)
      - prefix(github.com/cosmos/cosmos-sdk)
      - prefix(github.com/terpnetwork/terp-core)

  gosec:
    excludes:
      - G404  # Allow math/rand (for test/data generation, etc.)