#!/usr/bin/env bash
# Curate v6.1 artifacts for 120u-1 soak.
# Verifies ZK replaces, vendors patched store/v2 (BLAKE3 per store),
# records SOURCE_DEPS + wasm checksums. Does not upload, tag, or broadcast.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PACK="$ROOT/networks/upgrades/v6.1"
PATCH="$ROOT/app/iavlhash/store-v2-hasher.patch"
STORE_DEST="$ROOT/crates/cosmos/store-v2"
STORE_MOD="github.com/cosmos/cosmos-sdk/store/v2"
STORE_VER="v2.0.0"

sha256_file() {
  if command -v sha256sum >/dev/null; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

echo "=== curate v6.1 (120u-1) ==="
echo "  ROOT=$ROOT"

fail=0
for pair in \
  "github.com/CosmWasm/wasmd => ./crates/zk-wasmd" \
  "github.com/CosmWasm/wasmvm/v3 => ./crates/zk-wasmvm"
do
  if ! grep -F "$pair" go.mod >/dev/null; then
    echo "ERROR: missing go.mod replace: $pair" >&2
    fail=1
  fi
done
if grep -q 'github.com/CosmWasm/wasmvm/v3 => github.com/CosmWasm/wasmvm' go.mod; then
  echo "ERROR: stock wasmvm replace — ZK lineage required" >&2
  fail=1
fi
[ "$fail" -eq 0 ] || exit 1
echo "OK go.mod ZK replaces"

if [ -d "$ROOT/crates/cosmos/iavl" ] && ! grep -q 'github.com/cosmos/iavl => ./crates/cosmos/iavl' go.mod; then
  echo "NOTE: local crates/cosmos/iavl present but not replaced (BLAKE3 hasher is opt-in via store/v2 patch + iavl replace)"
fi

if [ ! -f "$PATCH" ]; then
  echo "ERROR: missing $PATCH" >&2
  exit 1
fi

GOMODCACHE="$(go env GOMODCACHE)"
STORE_SRC="$GOMODCACHE/${STORE_MOD}@${STORE_VER}"
if [ ! -d "$STORE_SRC" ]; then
  echo "==> downloading $STORE_MOD@$STORE_VER"
  GOWORK=off go mod download "$STORE_MOD@$STORE_VER"
fi
if [ ! -d "$STORE_SRC" ]; then
  echo "ERROR: $STORE_SRC not in module cache" >&2
  exit 1
fi

if [ ! -d "$STORE_DEST" ] || [ ! -f "$STORE_DEST/iavl/store.go" ]; then
  echo "==> vendor $STORE_MOD@$STORE_VER → crates/cosmos/store-v2"
  rm -rf "$STORE_DEST"
  mkdir -p "$(dirname "$STORE_DEST")"
  cp -R "$STORE_SRC" "$STORE_DEST"
  chmod -R u+w "$STORE_DEST"
fi

if ! grep -q 'HasherOptionForStore' "$STORE_DEST/iavl/store.go"; then
  echo "==> apply store-v2-hasher.patch"
  (cd "$STORE_DEST" && patch -p1 < "$PATCH")
fi
grep -q 'HasherOptionForStore' "$STORE_DEST/iavl/store.go" || {
  echo "ERROR: hasher patch did not land in $STORE_DEST/iavl/store.go" >&2
  exit 1
}

if ! grep -q "replace ${STORE_MOD} => ./crates/cosmos/store-v2" go.mod; then
  echo "==> go.mod replace store/v2 → ./crates/cosmos/store-v2"
  GOWORK=off go mod edit -replace="${STORE_MOD}=./crates/cosmos/store-v2"
fi
echo "OK store/v2 hasher replace"

if [ -f artifacts/polytone_listener.wasm ] && [ ! -f tests/interchaintest/contracts/polytone_listener.wasm ]; then
  mkdir -p tests/interchaintest/contracts
  cp -f artifacts/polytone_listener.wasm tests/interchaintest/contracts/polytone_listener.wasm
fi
if [ -f artifacts/norick_vk.bin ]; then
  mkdir -p tests/interchaintest/circuits
  cp -f artifacts/norick_vk.bin tests/interchaintest/circuits/no_rick.bin
fi

mkdir -p "$PACK"
{
  echo "# Regenerated by scripts/release/curate_v61.sh — do not invent S3 checksums."
  echo "# Plan v6.1. Chain 120u-1."
  echo
  echo "terp-core  $(git remote get-url origin 2>/dev/null || echo https://github.com/terpnetwork/terp-core.git)  $(git branch --show-current)  $(git rev-parse HEAD)  $(git describe --tags --always --dirty)"
  echo "cosmwasm   $(git -C crates/cosmwasm rev-parse HEAD)  $(git -C crates/cosmwasm describe --tags --always --dirty)"
  echo "wasmd      $(git -C crates/zk-wasmd rev-parse HEAD)  $(git -C crates/zk-wasmd describe --tags --always --dirty)"
  echo "wasmvm     $(git -C crates/zk-wasmvm rev-parse HEAD)  $(git -C crates/zk-wasmvm describe --tags --always --dirty)"
  if [ -d crates/cosmos/iavl/.git ] || [ -f crates/cosmos/iavl/.git ]; then
    echo "iavl       $(git -C crates/cosmos/iavl rev-parse HEAD)  $(git -C crates/cosmos/iavl describe --tags --always --dirty)"
  fi
  echo "store/v2   $STORE_MOD@$STORE_VER + app/iavlhash/store-v2-hasher.patch"
  echo
  echo "replaces:"
  grep -E 'wasmd|wasmvm/v3|cosmos/iavl |store/v2' go.mod | grep -E '=>|replace' || true
} > "$PACK/SOURCE_DEPS.txt"

{
  echo "# sha256  path  (repo-relative)"
  for f in \
    artifacts/polytone_listener.wasm \
    artifacts/polytone_note.wasm \
    artifacts/polytone_proxy.wasm \
    artifacts/polytone_voice.wasm \
    artifacts/polytone_tester.wasm \
    artifacts/cw_norick.wasm \
    artifacts/zk_wasmvm_test.wasm \
    artifacts/clock_example.wasm \
    artifacts/tokenfactory_core.wasm \
    artifacts/ibchooks_counter.wasm \
    artifacts/norick_vk.bin \
    tests/interchaintest/circuits/no_rick.bin
  do
    if [ -f "$f" ]; then
      echo "$(sha256_file "$f")  $f"
    else
      echo "MISSING  $f"
    fi
  done
} > "$PACK/STATIC_ASSETS.txt"

echo "wrote $PACK/SOURCE_DEPS.txt"
echo "wrote $PACK/STATIC_ASSETS.txt"
cat "$PACK/SOURCE_DEPS.txt"
echo
if command -v terpd >/dev/null; then
  echo "local terpd: $(command -v terpd)  $($(command -v terpd) version 2>/dev/null | head -1)"
fi
echo "OK curate complete. Do not submit gov. See $PACK/WORKFLOW.md"
