#!/usr/bin/env bash
# Shared helpers for sync_upgrade_pack.sh and verify_upgrade_pack.sh.
# Cosmovisor pack identity: one checksum set, written once, verified fail-closed.
# Do not source from PATH; callers live in scripts/release/.

sha256_file() {
  if command -v sha256sum >/dev/null; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

require_cmd() {
  command -v "$1" >/dev/null || {
    echo "ERROR: $1 is required" >&2
    exit 1
  }
}

require_exact_tag() {
  local tag="$1"
  if ! echo "$tag" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "ERROR: tag must be vX.Y.Z (got '${tag:-<empty>}'). No -dev, -rc, or git-describe." >&2
    exit 1
  fi
}

pack_dir() {
  echo "${PACK:-$ROOT/networks/upgrades/${PLAN}}"
}

lock_path() {
  echo "$(pack_dir)/ARTIFACT_LOCK"
}

lock_field() {
  local lock="$1" key="$2"
  awk -F': ' -v k="$key" '$1 == k {print $2; exit}' "$lock"
}

# Print "<sha256> <basename>" lines from ARTIFACT_LOCK.
lock_sum_lines() {
  awk '/^[0-9a-f]{64}  / {print $1, $2}' "$1"
}

lock_sum_for() {
  local lock="$1" name="$2"
  lock_sum_lines "$lock" | awk -v n="$name" '$2 == n {print $1; exit}'
}

has_checksum_lock() {
  local lock="$1"
  [ -f "$lock" ] && grep -Eq '^[0-9a-f]{64}  terpd-' "$lock"
}

gitlink_sha() {
  local commit="$1" path="$2"
  git ls-tree "$commit" "$path" | awk '{print $3}'
}

submodule_url() {
  local commit="$1" path="$2"
  git show "$commit:.gitmodules" 2>/dev/null | awk -v p="$path" '
    $0 ~ "path = " p {hit=1}
    hit && $1 == "url" {print $3; exit}
  '
}

compact_json_file() {
  jq -c . "$1"
}

# Rewrite plan.info for every message whose plan.name matches.
set_plan_info() {
  local file="$1" name="$2" compact="$3"
  local tmp
  tmp="$(mktemp)"
  jq --arg name "$name" --arg info "$compact" '
    .messages |= map(if .plan.name == $name then .plan.info = $info else . end)
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

write_source_deps() {
  local pack="$1" commit="$2" tag="$3" plan="$4"
  local out="$pack/SOURCE_DEPS.txt"
  local origin wasmd_sha wasmvm_sha cosmwasm_sha wasmd_url wasmvm_url cosmwasm_url
  origin="$(git remote get-url origin 2>/dev/null || echo https://github.com/terpnetwork/terp-core.git)"
  wasmd_sha="$(gitlink_sha "$commit" crates/zk-wasmd)"
  wasmvm_sha="$(gitlink_sha "$commit" crates/zk-wasmvm)"
  cosmwasm_sha="$(gitlink_sha "$commit" crates/cosmwasm)"
  if [ -z "$wasmd_sha" ] || [ -z "$wasmvm_sha" ] || [ -z "$cosmwasm_sha" ]; then
    echo "ERROR: missing gitlinks at $commit (zk-wasmd / zk-wasmvm / cosmwasm)" >&2
    exit 1
  fi
  wasmd_url="$(submodule_url "$commit" crates/zk-wasmd)"
  wasmvm_url="$(submodule_url "$commit" crates/zk-wasmvm)"
  cosmwasm_url="$(submodule_url "$commit" crates/cosmwasm)"
  {
    echo "# Generated by scripts/release/sync_upgrade_pack.sh from gitlinks at binary_commit."
    echo "# Do not hand-edit. Re-run: PLAN=$plan make sync-upgrade-pack"
    echo "# ELF identity is git tag $tag = $commit. Pack files belong on release/$tag."
    echo
    echo "terp-core  $origin  $tag  $commit"
    echo "wasmd      ${wasmd_url:-https://github.com/permissionlessweb/wasmd}  $wasmd_sha  crates/zk-wasmd"
    echo "wasmvm     ${wasmvm_url:-https://github.com/permissionlessweb/wasmvm}  $wasmvm_sha  crates/zk-wasmvm"
    echo "cosmwasm   ${cosmwasm_url:-https://github.com/permissionlessweb/cosmwasm.git}  $cosmwasm_sha  crates/cosmwasm"
    echo
    echo "replaces (go.mod at binary_commit):"
    git show "$commit:go.mod" | grep -E '=>|replace ' | grep -E 'wasmd|wasmvm/v3|iavl|store/v2' | grep -v '^//' || true
    echo
    echo "wasmvm muslc (do not rebuild; fetch + sha256, Path A STWO):"
    echo "  base https://minio.terp.network/releases/zk-wasmvm/v3.0.7-zk/"
    echo "  0687e59140c967a752b0b0ede98e71a3c859fb4f6b94fc26883792d381eb4716  libwasmvm_muslc.aarch64.a"
    echo "  4f4880e1655d34c098729df52db22c9253bec87d2b3185669ff015a340b76d49  libwasmvm_muslc.x86_64.a"
  } > "$out"
}

write_binaries_json() {
  local tag="$1" sums_file="$2" out="$3" base_url="$4"
  python3 "$ROOT/scripts/release/create_binaries_json/create_binaries_json.py" \
    --tag "$tag" \
    --checksums_file "$sums_file" \
    --base-url "$base_url" \
    --out "$out"
}

# Hex from a SOURCE_DEPS identity line (first 40-char sha).
deps_sha() {
  local file="$1" key="$2"
  awk -v k="$key" '$1 == k {
    for (i = 2; i <= NF; i++) if ($i ~ /^[0-9a-f]{40}$/) { print $i; exit }
  }' "$file"
}
