[package]
name = "flock-hash"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Hash primitives used by Flock protocols."

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
