[package]
name = "nested-contracts"
version = "0.0.0"
authors = ["Aumetra Weisman <aumetra@cryptolab.net>"]
edition = "2021"
publish = false
license = "Apache-2.0"

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/optimizer:0.15.0
"""

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = { path = "../../packages/schema" }
# Enable "cosmwasm_2_0" feature if you only deploy to chains that have CosmWasm 2.0 or higher.
cosmwasm-std = { path = "../../packages/std", features = ["cosmwasm_1_4"] }
cw-storage-plus = { path = "../../../cw-storage-plus" }
cw2 = { path = "../../../cw-minus/packages/cw2" }
inner-contract = { path = "./inner-contract" }
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.58" }

[dev-dependencies]
cw-multi-test = { package = "abstract-cw-multi-test", path = "../../../cw-multi-test-fork" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
