// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terp/hashmerchant/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the configurable parameters of x/hashmerchant.
type Params struct {
	// quorum_fraction is the minimum fraction of voting power required to accept
	// a hash root (e.g. "0.667").
	QuorumFraction cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=quorum_fraction,json=quorumFraction,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"quorum_fraction"`
	// prune_interval is the number of blocks between automatic pruning runs.
	PruneInterval uint64 `protobuf:"varint,2,opt,name=prune_interval,json=pruneInterval,proto3" json:"prune_interval,omitempty"`
	// escrow_denom is the token denom required for contract escrow payments.
	EscrowDenom string `protobuf:"bytes,3,opt,name=escrow_denom,json=escrowDenom,proto3" json:"escrow_denom,omitempty"`
	// min_escrow_amount is the minimum escrow deposit per registration period.
	MinEscrowAmount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=min_escrow_amount,json=minEscrowAmount,proto3,customtype=cosmossdk.io/math.Int" json:"min_escrow_amount"`
	// market_mode selects open or closed attestation market.
	MarketMode MarketMode `protobuf:"varint,5,opt,name=market_mode,json=marketMode,proto3,enum=terp.hashmerchant.v1.MarketMode" json:"market_mode,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_78efba81f014c5f2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPruneInterval() uint64 {
	if m != nil {
		return m.PruneInterval
	}
	return 0
}

func (m *Params) GetEscrowDenom() string {
	if m != nil {
		return m.EscrowDenom
	}
	return ""
}

func (m *Params) GetMarketMode() MarketMode {
	if m != nil {
		return m.MarketMode
	}
	return MarketMode_MARKET_MODE_UNSPECIFIED
}

// GenesisState defines the x/hashmerchant module genesis.
type GenesisState struct {
	Params              Params               `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	RegisteredChains    []RegisteredChain    `protobuf:"bytes,2,rep,name=registered_chains,json=registeredChains,proto3" json:"registered_chains"`
	RegisteredContracts []RegisteredContract `protobuf:"bytes,3,rep,name=registered_contracts,json=registeredContracts,proto3" json:"registered_contracts"`
	EscrowRecords       []EscrowRecord       `protobuf:"bytes,4,rep,name=escrow_records,json=escrowRecords,proto3" json:"escrow_records"`
	HashRoots           []HashRoot           `protobuf:"bytes,5,rep,name=hash_roots,json=hashRoots,proto3" json:"hash_roots"`
	PruneEpoch          uint64               `protobuf:"varint,6,opt,name=prune_epoch,json=pruneEpoch,proto3" json:"prune_epoch,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_78efba81f014c5f2, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRegisteredChains() []RegisteredChain {
	if m != nil {
		return m.RegisteredChains
	}
	return nil
}

func (m *GenesisState) GetRegisteredContracts() []RegisteredContract {
	if m != nil {
		return m.RegisteredContracts
	}
	return nil
}

func (m *GenesisState) GetEscrowRecords() []EscrowRecord {
	if m != nil {
		return m.EscrowRecords
	}
	return nil
}

func (m *GenesisState) GetHashRoots() []HashRoot {
	if m != nil {
		return m.HashRoots
	}
	return nil
}

func (m *GenesisState) GetPruneEpoch() uint64 {
	if m != nil {
		return m.PruneEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "terp.hashmerchant.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "terp.hashmerchant.v1.GenesisState")
}

func init() {
	proto.RegisterFile("terp/hashmerchant/v1/genesis.proto", fileDescriptor_78efba81f014c5f2)
}

var fileDescriptor_78efba81f014c5f2 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0x26, 0x8d, 0xd4, 0x4d, 0x9b, 0xd2, 0xa5, 0x48, 0x56, 0x01, 0xd7, 0x04, 0x55,
	0xca, 0x05, 0x5b, 0x2d, 0x42, 0x42, 0xdc, 0xfa, 0x0f, 0x88, 0xd4, 0x0a, 0x64, 0x2e, 0x88, 0x8b,
	0xb5, 0xb5, 0x07, 0xdb, 0x0a, 0xbb, 0x63, 0x76, 0x37, 0x29, 0x7d, 0x0b, 0x9e, 0x84, 0x47, 0xe0,
	0xdc, 0x63, 0x8f, 0x88, 0x43, 0x85, 0x92, 0x17, 0x41, 0x5e, 0x2f, 0x55, 0xaa, 0x5a, 0xe2, 0xb6,
	0xfe, 0xfc, 0x7d, 0xbf, 0x1d, 0xcd, 0xec, 0x90, 0x81, 0x06, 0x59, 0x86, 0x39, 0x53, 0x39, 0x07,
	0x99, 0xe4, 0x4c, 0xe8, 0x70, 0xba, 0x1b, 0x66, 0x20, 0x40, 0x15, 0x2a, 0x28, 0x25, 0x6a, 0xa4,
	0x9b, 0x95, 0x27, 0x58, 0xf4, 0x04, 0xd3, 0xdd, 0xad, 0xcd, 0x0c, 0x33, 0x34, 0x86, 0xb0, 0x3a,
	0xd5, 0xde, 0x2d, 0xbf, 0x91, 0xa7, 0x2f, 0x4a, 0xb0, 0xb4, 0xc1, 0x8f, 0x25, 0xd2, 0x7d, 0xcf,
	0x24, 0xe3, 0x8a, 0x9e, 0x90, 0xf5, 0xaf, 0x13, 0x94, 0x13, 0x1e, 0x7f, 0x96, 0x2c, 0xd1, 0x05,
	0x0a, 0xd7, 0xf1, 0x9d, 0xe1, 0xca, 0xc1, 0xd3, 0xcb, 0xeb, 0xed, 0xd6, 0xef, 0xeb, 0xed, 0x87,
	0x09, 0x2a, 0x8e, 0x4a, 0xa5, 0xe3, 0xa0, 0xc0, 0x90, 0x33, 0x9d, 0x07, 0x27, 0x90, 0xb1, 0xe4,
	0xe2, 0x08, 0x92, 0xa8, 0x5f, 0x67, 0x5f, 0xdb, 0x28, 0xdd, 0x21, 0xfd, 0x52, 0x4e, 0x04, 0xc4,
	0x85, 0xd0, 0x20, 0xa7, 0xec, 0x8b, 0xbb, 0xe4, 0x3b, 0xc3, 0x4e, 0xb4, 0x66, 0xd4, 0x91, 0x15,
	0xe9, 0x13, 0xb2, 0x0a, 0x2a, 0x91, 0x78, 0x1e, 0xa7, 0x20, 0x90, 0xbb, 0xed, 0xea, 0xc6, 0xa8,
	0x57, 0x6b, 0x47, 0x95, 0x44, 0x47, 0x64, 0x83, 0x17, 0x22, 0xb6, 0x36, 0xc6, 0x71, 0x22, 0xb4,
	0xdb, 0x31, 0x95, 0x3d, 0xb6, 0x95, 0x3d, 0xb8, 0x5b, 0xd9, 0x48, 0xe8, 0x68, 0x9d, 0x17, 0xe2,
	0xd8, 0xc4, 0xf6, 0x4d, 0x8a, 0xee, 0x93, 0x1e, 0x67, 0x72, 0x0c, 0x3a, 0xe6, 0x98, 0x82, 0xbb,
	0xec, 0x3b, 0xc3, 0xfe, 0x9e, 0x1f, 0x34, 0x75, 0x34, 0x38, 0x35, 0xc6, 0x53, 0x4c, 0x21, 0x22,
	0xfc, 0xe6, 0x3c, 0xf8, 0xd9, 0x26, 0xab, 0x6f, 0xea, 0x81, 0x7c, 0xd0, 0x4c, 0x03, 0x7d, 0x45,
	0xba, 0xa5, 0x69, 0xa0, 0xe9, 0x56, 0x6f, 0xef, 0x51, 0x33, 0xae, 0x6e, 0xf2, 0x41, 0xa7, 0xaa,
	0x38, 0xb2, 0x09, 0xfa, 0x91, 0x6c, 0x48, 0xc8, 0x0a, 0xa5, 0x41, 0x42, 0x1a, 0x27, 0x39, 0x2b,
	0x84, 0x72, 0x97, 0xfc, 0xf6, 0xb0, 0xb7, 0xb7, 0xd3, 0x8c, 0x89, 0x6e, 0xec, 0x87, 0x95, 0xdb,
	0xf2, 0xee, 0xc9, 0xdb, 0xb2, 0xa2, 0x8c, 0x6c, 0x2e, 0x92, 0x51, 0xe8, 0x6a, 0x30, 0xca, 0x6d,
	0x1b, 0xf8, 0xf0, 0xbf, 0x70, 0x1b, 0xb0, 0xfc, 0xfb, 0xf2, 0xce, 0x1f, 0x45, 0xdf, 0x91, 0xbe,
	0x9d, 0x89, 0x84, 0x04, 0x65, 0xaa, 0xdc, 0x8e, 0x81, 0x0f, 0x9a, 0xe1, 0xf5, 0x20, 0x22, 0x63,
	0xb5, 0xd8, 0x35, 0x58, 0xd0, 0x14, 0x3d, 0x24, 0xa4, 0x0a, 0xc5, 0x12, 0x51, 0x2b, 0x77, 0xd9,
	0xc0, 0xbc, 0x66, 0xd8, 0x5b, 0xa6, 0xf2, 0x08, 0xf1, 0x5f, 0x7d, 0x2b, 0xb9, 0xfd, 0x56, 0x74,
	0x9b, 0xf4, 0xea, 0x77, 0x07, 0x25, 0x26, 0xb9, 0xdb, 0x35, 0x8f, 0x8e, 0x18, 0xe9, 0xb8, 0x52,
	0x0e, 0xa2, 0xcb, 0x99, 0xe7, 0x5c, 0xcd, 0x3c, 0xe7, 0xcf, 0xcc, 0x73, 0xbe, 0xcf, 0xbd, 0xd6,
	0xd5, 0xdc, 0x6b, 0xfd, 0x9a, 0x7b, 0xad, 0x4f, 0x2f, 0xb3, 0x42, 0xe7, 0x93, 0xb3, 0x20, 0x41,
	0x1e, 0x56, 0xb7, 0x0a, 0xd0, 0xe7, 0x28, 0xc7, 0xe6, 0xfc, 0x2c, 0x41, 0x09, 0xe1, 0xf4, 0x45,
	0xf8, 0xed, 0xf6, 0x3a, 0x99, 0x5d, 0x3a, 0xeb, 0x9a, 0x65, 0x7a, 0xfe, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x7e, 0xb9, 0xcc, 0xc0, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MarketMode != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MarketMode))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.MinEscrowAmount.Size()
		i -= size
		if _, err := m.MinEscrowAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.EscrowDenom) > 0 {
		i -= len(m.EscrowDenom)
		copy(dAtA[i:], m.EscrowDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.EscrowDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PruneInterval != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PruneInterval))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.QuorumFraction.Size()
		i -= size
		if _, err := m.QuorumFraction.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PruneEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PruneEpoch))
		i--
		dAtA[i] = 0x30
	}
	if len(m.HashRoots) > 0 {
		for iNdEx := len(m.HashRoots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HashRoots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.EscrowRecords) > 0 {
		for iNdEx := len(m.EscrowRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EscrowRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RegisteredContracts) > 0 {
		for iNdEx := len(m.RegisteredContracts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegisteredContracts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RegisteredChains) > 0 {
		for iNdEx := len(m.RegisteredChains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegisteredChains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.QuorumFraction.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.PruneInterval != 0 {
		n += 1 + sovGenesis(uint64(m.PruneInterval))
	}
	l = len(m.EscrowDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.MinEscrowAmount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.MarketMode != 0 {
		n += 1 + sovGenesis(uint64(m.MarketMode))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.RegisteredChains) > 0 {
		for _, e := range m.RegisteredChains {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RegisteredContracts) > 0 {
		for _, e := range m.RegisteredContracts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.EscrowRecords) > 0 {
		for _, e := range m.EscrowRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HashRoots) > 0 {
		for _, e := range m.HashRoots {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PruneEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.PruneEpoch))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QuorumFraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PruneInterval", wireType)
			}
			m.PruneInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PruneInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinEscrowAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinEscrowAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketMode", wireType)
			}
			m.MarketMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketMode |= MarketMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredChains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegisteredChains = append(m.RegisteredChains, RegisteredChain{})
			if err := m.RegisteredChains[len(m.RegisteredChains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredContracts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegisteredContracts = append(m.RegisteredContracts, RegisteredContract{})
			if err := m.RegisteredContracts[len(m.RegisteredContracts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowRecords = append(m.EscrowRecords, EscrowRecord{})
			if err := m.EscrowRecords[len(m.EscrowRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashRoots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashRoots = append(m.HashRoots, HashRoot{})
			if err := m.HashRoots[len(m.HashRoots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PruneEpoch", wireType)
			}
			m.PruneEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PruneEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
