// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terp/hashmerchant/v1/types.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MarketMode governs who may provide hash attestations.
type MarketMode int32

const (
	MarketMode_MARKET_MODE_UNSPECIFIED MarketMode = 0
	// Open: any validator may attest.
	MarketMode_MARKET_MODE_OPEN MarketMode = 1
	// Closed: only governance-whitelisted providers may attest.
	MarketMode_MARKET_MODE_CLOSED MarketMode = 2
)

var MarketMode_name = map[int32]string{
	0: "MARKET_MODE_UNSPECIFIED",
	1: "MARKET_MODE_OPEN",
	2: "MARKET_MODE_CLOSED",
}

var MarketMode_value = map[string]int32{
	"MARKET_MODE_UNSPECIFIED": 0,
	"MARKET_MODE_OPEN":        1,
	"MARKET_MODE_CLOSED":      2,
}

func (x MarketMode) String() string {
	return proto.EnumName(MarketMode_name, int32(x))
}

func (MarketMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{0}
}

// OracleSourceKind identifies a modular data-source type (Skip-Connect-style).
type OracleSourceKind int32

const (
	OracleSourceKind_ORACLE_SOURCE_KIND_UNSPECIFIED OracleSourceKind = 0
	OracleSourceKind_ORACLE_SOURCE_KIND_POSTGRES    OracleSourceKind = 1
	OracleSourceKind_ORACLE_SOURCE_KIND_BITCOIN_RPC OracleSourceKind = 2
	OracleSourceKind_ORACLE_SOURCE_KIND_ZCASH_RPC   OracleSourceKind = 3
	OracleSourceKind_ORACLE_SOURCE_KIND_HTTP        OracleSourceKind = 4
	OracleSourceKind_ORACLE_SOURCE_KIND_CUSTOM      OracleSourceKind = 5
)

var OracleSourceKind_name = map[int32]string{
	0: "ORACLE_SOURCE_KIND_UNSPECIFIED",
	1: "ORACLE_SOURCE_KIND_POSTGRES",
	2: "ORACLE_SOURCE_KIND_BITCOIN_RPC",
	3: "ORACLE_SOURCE_KIND_ZCASH_RPC",
	4: "ORACLE_SOURCE_KIND_HTTP",
	5: "ORACLE_SOURCE_KIND_CUSTOM",
}

var OracleSourceKind_value = map[string]int32{
	"ORACLE_SOURCE_KIND_UNSPECIFIED": 0,
	"ORACLE_SOURCE_KIND_POSTGRES":    1,
	"ORACLE_SOURCE_KIND_BITCOIN_RPC": 2,
	"ORACLE_SOURCE_KIND_ZCASH_RPC":   3,
	"ORACLE_SOURCE_KIND_HTTP":        4,
	"ORACLE_SOURCE_KIND_CUSTOM":      5,
}

func (x OracleSourceKind) String() string {
	return proto.EnumName(OracleSourceKind_name, int32(x))
}

func (OracleSourceKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{1}
}

// CustodyAuthenticator limits signing surface area per source (Penumbra-style).
// Only attestations whose domain matches `scope` and verify under `pubkey` are accepted.
type CustodyAuthenticator struct {
	// ed25519 or secp256k1 public key bytes
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// signing algorithm: "ed25519" | "secp256k1"
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// allowed attestation scope, e.g. "merkle_root", "price_feed"
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
}

func (m *CustodyAuthenticator) Reset()         { *m = CustodyAuthenticator{} }
func (m *CustodyAuthenticator) String() string { return proto.CompactTextString(m) }
func (*CustodyAuthenticator) ProtoMessage()    {}
func (*CustodyAuthenticator) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{0}
}
func (m *CustodyAuthenticator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyAuthenticator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyAuthenticator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyAuthenticator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyAuthenticator.Merge(m, src)
}
func (m *CustodyAuthenticator) XXX_Size() int {
	return m.Size()
}
func (m *CustodyAuthenticator) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyAuthenticator.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyAuthenticator proto.InternalMessageInfo

func (m *CustodyAuthenticator) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *CustodyAuthenticator) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *CustodyAuthenticator) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

// OracleSource is a registered modular data source for a chain_uid.
// Mirrors IBCv2 CounterpartyInfo modularity: each source has its own merkle prefix
// and custody-bound authenticator rather than trusting a monolithic sidecar response.
type OracleSource struct {
	// unique id within the chain_uid, e.g. "loyalty-db", "btc-usd", "zec-usd"
	SourceId string           `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Kind     OracleSourceKind `protobuf:"varint,2,opt,name=kind,proto3,enum=terp.hashmerchant.v1.OracleSourceKind" json:"kind,omitempty"`
	// endpoint URL or connection string the sidecar queries
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// IBCv2-style merkle prefix for membership proofs from this source
	MerklePrefix [][]byte `protobuf:"bytes,4,rep,name=merkle_prefix,json=merklePrefix,proto3" json:"merkle_prefix,omitempty"`
	// custody authenticator limiting what this source may attest
	Authenticator *CustodyAuthenticator `protobuf:"bytes,5,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	Enabled       bool                  `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *OracleSource) Reset()         { *m = OracleSource{} }
func (m *OracleSource) String() string { return proto.CompactTextString(m) }
func (*OracleSource) ProtoMessage()    {}
func (*OracleSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{1}
}
func (m *OracleSource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleSource.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleSource.Merge(m, src)
}
func (m *OracleSource) XXX_Size() int {
	return m.Size()
}
func (m *OracleSource) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleSource.DiscardUnknown(m)
}

var xxx_messageInfo_OracleSource proto.InternalMessageInfo

func (m *OracleSource) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *OracleSource) GetKind() OracleSourceKind {
	if m != nil {
		return m.Kind
	}
	return OracleSourceKind_ORACLE_SOURCE_KIND_UNSPECIFIED
}

func (m *OracleSource) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *OracleSource) GetMerklePrefix() [][]byte {
	if m != nil {
		return m.MerklePrefix
	}
	return nil
}

func (m *OracleSource) GetAuthenticator() *CustodyAuthenticator {
	if m != nil {
		return m.Authenticator
	}
	return nil
}

func (m *OracleSource) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// RegisteredChain describes a foreign blockchain whose substore roots
// validators will mirror via vote extensions.
type RegisteredChain struct {
	// chain_uid is the unique identifier (e.g. "cosmoshub-4", "ethereum-mainnet").
	ChainUid string `protobuf:"bytes,1,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	// human-readable label
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// rpc_endpoints that validator runtimes may query
	RpcEndpoints []string `protobuf:"bytes,3,rep,name=rpc_endpoints,json=rpcEndpoints,proto3" json:"rpc_endpoints,omitempty"`
	// hash_algos this chain supports (e.g. "sha256", "keccak256", "poseidon")
	HashAlgos []string `protobuf:"bytes,4,rep,name=hash_algos,json=hashAlgos,proto3" json:"hash_algos,omitempty"`
	// enabled toggles attestation acceptance
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// modular oracle sources aggregated by the sidecar (IBCv2 workflow)
	OracleSources []*OracleSource `protobuf:"bytes,6,rep,name=oracle_sources,json=oracleSources,proto3" json:"oracle_sources,omitempty"`
}

func (m *RegisteredChain) Reset()         { *m = RegisteredChain{} }
func (m *RegisteredChain) String() string { return proto.CompactTextString(m) }
func (*RegisteredChain) ProtoMessage()    {}
func (*RegisteredChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{2}
}
func (m *RegisteredChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisteredChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisteredChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisteredChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredChain.Merge(m, src)
}
func (m *RegisteredChain) XXX_Size() int {
	return m.Size()
}
func (m *RegisteredChain) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredChain.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredChain proto.InternalMessageInfo

func (m *RegisteredChain) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *RegisteredChain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisteredChain) GetRpcEndpoints() []string {
	if m != nil {
		return m.RpcEndpoints
	}
	return nil
}

func (m *RegisteredChain) GetHashAlgos() []string {
	if m != nil {
		return m.HashAlgos
	}
	return nil
}

func (m *RegisteredChain) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *RegisteredChain) GetOracleSources() []*OracleSource {
	if m != nil {
		return m.OracleSources
	}
	return nil
}

// OracleAttestation is a per-source signed value bundled in VoteExtensionHashData.
type OracleAttestation struct {
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// attested value (e.g. merkle root bytes or price feed digest)
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Height    uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// custody signature over domain-separated payload
	CustodySignature []byte `protobuf:"bytes,5,opt,name=custody_signature,json=custodySignature,proto3" json:"custody_signature,omitempty"`
	// optional ICS-23 proof for this source's value
	Ics23Proof []byte `protobuf:"bytes,6,opt,name=ics23_proof,json=ics23Proof,proto3" json:"ics23_proof,omitempty"`
}

func (m *OracleAttestation) Reset()         { *m = OracleAttestation{} }
func (m *OracleAttestation) String() string { return proto.CompactTextString(m) }
func (*OracleAttestation) ProtoMessage()    {}
func (*OracleAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{3}
}
func (m *OracleAttestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleAttestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleAttestation.Merge(m, src)
}
func (m *OracleAttestation) XXX_Size() int {
	return m.Size()
}
func (m *OracleAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_OracleAttestation proto.InternalMessageInfo

func (m *OracleAttestation) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *OracleAttestation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *OracleAttestation) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *OracleAttestation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OracleAttestation) GetCustodySignature() []byte {
	if m != nil {
		return m.CustodySignature
	}
	return nil
}

func (m *OracleAttestation) GetIcs23Proof() []byte {
	if m != nil {
		return m.Ics23Proof
	}
	return nil
}

// RegisteredContract is a CosmWasm contract that has paid escrow to receive
// sudo callbacks when new hash roots are confirmed.
type RegisteredContract struct {
	ContractAddr string `protobuf:"bytes,1,opt,name=contract_addr,json=contractAddr,proto3" json:"contract_addr,omitempty"`
	ChainUid     string `protobuf:"bytes,2,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	// substore_keys the contract is interested in (e.g. ["bank", "staking"])
	SubstoreKeys []string `protobuf:"bytes,3,rep,name=substore_keys,json=substoreKeys,proto3" json:"substore_keys,omitempty"`
	Enabled      bool     `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *RegisteredContract) Reset()         { *m = RegisteredContract{} }
func (m *RegisteredContract) String() string { return proto.CompactTextString(m) }
func (*RegisteredContract) ProtoMessage()    {}
func (*RegisteredContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{4}
}
func (m *RegisteredContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisteredContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisteredContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisteredContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredContract.Merge(m, src)
}
func (m *RegisteredContract) XXX_Size() int {
	return m.Size()
}
func (m *RegisteredContract) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredContract.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredContract proto.InternalMessageInfo

func (m *RegisteredContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *RegisteredContract) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *RegisteredContract) GetSubstoreKeys() []string {
	if m != nil {
		return m.SubstoreKeys
	}
	return nil
}

func (m *RegisteredContract) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// EscrowRecord tracks the escrow deposit for a registered contract.
type EscrowRecord struct {
	ContractAddr string     `protobuf:"bytes,1,opt,name=contract_addr,json=contractAddr,proto3" json:"contract_addr,omitempty"`
	Amount       types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	// height through which the escrow is paid
	PaidUntilHeight uint64 `protobuf:"varint,3,opt,name=paid_until_height,json=paidUntilHeight,proto3" json:"paid_until_height,omitempty"`
	LastPruneHeight uint64 `protobuf:"varint,4,opt,name=last_prune_height,json=lastPruneHeight,proto3" json:"last_prune_height,omitempty"`
}

func (m *EscrowRecord) Reset()         { *m = EscrowRecord{} }
func (m *EscrowRecord) String() string { return proto.CompactTextString(m) }
func (*EscrowRecord) ProtoMessage()    {}
func (*EscrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{5}
}
func (m *EscrowRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EscrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EscrowRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EscrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowRecord.Merge(m, src)
}
func (m *EscrowRecord) XXX_Size() int {
	return m.Size()
}
func (m *EscrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowRecord proto.InternalMessageInfo

func (m *EscrowRecord) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *EscrowRecord) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EscrowRecord) GetPaidUntilHeight() uint64 {
	if m != nil {
		return m.PaidUntilHeight
	}
	return 0
}

func (m *EscrowRecord) GetLastPruneHeight() uint64 {
	if m != nil {
		return m.LastPruneHeight
	}
	return 0
}

// HashRoot is a confirmed foreign-chain state root stored on-chain after
// reaching validator quorum via vote extensions.
type HashRoot struct {
	ChainUid string `protobuf:"bytes,1,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	Algo     string `protobuf:"bytes,2,opt,name=algo,proto3" json:"algo,omitempty"`
	Height   uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Root     []byte `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	// number of validators that attested to this root
	AttestationCount uint32 `protobuf:"varint,5,opt,name=attestation_count,json=attestationCount,proto3" json:"attestation_count,omitempty"`
	// block_time of the foreign chain (unix seconds)
	BlockTime int64 `protobuf:"varint,6,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	// confirmed per-source attestations included in this root round
	Attestations []*OracleAttestation `protobuf:"bytes,7,rep,name=attestations,proto3" json:"attestations,omitempty"`
}

func (m *HashRoot) Reset()         { *m = HashRoot{} }
func (m *HashRoot) String() string { return proto.CompactTextString(m) }
func (*HashRoot) ProtoMessage()    {}
func (*HashRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{6}
}
func (m *HashRoot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashRoot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRoot.Merge(m, src)
}
func (m *HashRoot) XXX_Size() int {
	return m.Size()
}
func (m *HashRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRoot.DiscardUnknown(m)
}

var xxx_messageInfo_HashRoot proto.InternalMessageInfo

func (m *HashRoot) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *HashRoot) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *HashRoot) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HashRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *HashRoot) GetAttestationCount() uint32 {
	if m != nil {
		return m.AttestationCount
	}
	return 0
}

func (m *HashRoot) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *HashRoot) GetAttestations() []*OracleAttestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

// HashPairTicket is the core on-chain primitive: a filterable, zk-optimised
// pair of hashes linking an origin chain state to a destination representation.
type HashPairTicket struct {
	ProjectId          string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	OriginHash         []byte `protobuf:"bytes,2,opt,name=origin_hash,json=originHash,proto3" json:"origin_hash,omitempty"`
	DestinationHash    []byte `protobuf:"bytes,3,opt,name=destination_hash,json=destinationHash,proto3" json:"destination_hash,omitempty"`
	ZkCircuitId        string `protobuf:"bytes,4,opt,name=zk_circuit_id,json=zkCircuitId,proto3" json:"zk_circuit_id,omitempty"`
	DestinationChainId uint64 `protobuf:"varint,5,opt,name=destination_chain_id,json=destinationChainId,proto3" json:"destination_chain_id,omitempty"`
	ExpiryBlock        uint64 `protobuf:"varint,6,opt,name=expiry_block,json=expiryBlock,proto3" json:"expiry_block,omitempty"`
	Metadata           []byte `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *HashPairTicket) Reset()         { *m = HashPairTicket{} }
func (m *HashPairTicket) String() string { return proto.CompactTextString(m) }
func (*HashPairTicket) ProtoMessage()    {}
func (*HashPairTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{7}
}
func (m *HashPairTicket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashPairTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashPairTicket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashPairTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashPairTicket.Merge(m, src)
}
func (m *HashPairTicket) XXX_Size() int {
	return m.Size()
}
func (m *HashPairTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_HashPairTicket.DiscardUnknown(m)
}

var xxx_messageInfo_HashPairTicket proto.InternalMessageInfo

func (m *HashPairTicket) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *HashPairTicket) GetOriginHash() []byte {
	if m != nil {
		return m.OriginHash
	}
	return nil
}

func (m *HashPairTicket) GetDestinationHash() []byte {
	if m != nil {
		return m.DestinationHash
	}
	return nil
}

func (m *HashPairTicket) GetZkCircuitId() string {
	if m != nil {
		return m.ZkCircuitId
	}
	return ""
}

func (m *HashPairTicket) GetDestinationChainId() uint64 {
	if m != nil {
		return m.DestinationChainId
	}
	return 0
}

func (m *HashPairTicket) GetExpiryBlock() uint64 {
	if m != nil {
		return m.ExpiryBlock
	}
	return 0
}

func (m *HashPairTicket) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// VoteExtensionHashData is the payload validators include in their ABCI++
// vote extensions.  It bundles a hash-pair ticket with the ICS-23 proof
// material that the on-chain module uses for verification.
type VoteExtensionHashData struct {
	RuntimeId        string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ChainUid         string `protobuf:"bytes,2,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	Algo             string `protobuf:"bytes,3,opt,name=algo,proto3" json:"algo,omitempty"`
	Root             []byte `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	ForeignHeight    uint64 `protobuf:"varint,5,opt,name=foreign_height,json=foreignHeight,proto3" json:"foreign_height,omitempty"`
	ForeignBlockTime int64  `protobuf:"varint,6,opt,name=foreign_block_time,json=foreignBlockTime,proto3" json:"foreign_block_time,omitempty"`
	// ics23_proof is an optional ICS-23 commitment proof for the root
	Ics23Proof []byte `protobuf:"bytes,7,opt,name=ics23_proof,json=ics23Proof,proto3" json:"ics23_proof,omitempty"`
	// per-source attestations aggregated by the sidecar (IBCv2 modular auth)
	Attestations []*OracleAttestation `protobuf:"bytes,8,rep,name=attestations,proto3" json:"attestations,omitempty"`
}

func (m *VoteExtensionHashData) Reset()         { *m = VoteExtensionHashData{} }
func (m *VoteExtensionHashData) String() string { return proto.CompactTextString(m) }
func (*VoteExtensionHashData) ProtoMessage()    {}
func (*VoteExtensionHashData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{8}
}
func (m *VoteExtensionHashData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteExtensionHashData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteExtensionHashData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteExtensionHashData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteExtensionHashData.Merge(m, src)
}
func (m *VoteExtensionHashData) XXX_Size() int {
	return m.Size()
}
func (m *VoteExtensionHashData) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteExtensionHashData.DiscardUnknown(m)
}

var xxx_messageInfo_VoteExtensionHashData proto.InternalMessageInfo

func (m *VoteExtensionHashData) GetRuntimeId() string {
	if m != nil {
		return m.RuntimeId
	}
	return ""
}

func (m *VoteExtensionHashData) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *VoteExtensionHashData) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *VoteExtensionHashData) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *VoteExtensionHashData) GetForeignHeight() uint64 {
	if m != nil {
		return m.ForeignHeight
	}
	return 0
}

func (m *VoteExtensionHashData) GetForeignBlockTime() int64 {
	if m != nil {
		return m.ForeignBlockTime
	}
	return 0
}

func (m *VoteExtensionHashData) GetIcs23Proof() []byte {
	if m != nil {
		return m.Ics23Proof
	}
	return nil
}

func (m *VoteExtensionHashData) GetAttestations() []*OracleAttestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func init() {
	proto.RegisterEnum("terp.hashmerchant.v1.MarketMode", MarketMode_name, MarketMode_value)
	proto.RegisterEnum("terp.hashmerchant.v1.OracleSourceKind", OracleSourceKind_name, OracleSourceKind_value)
	proto.RegisterType((*CustodyAuthenticator)(nil), "terp.hashmerchant.v1.CustodyAuthenticator")
	proto.RegisterType((*OracleSource)(nil), "terp.hashmerchant.v1.OracleSource")
	proto.RegisterType((*RegisteredChain)(nil), "terp.hashmerchant.v1.RegisteredChain")
	proto.RegisterType((*OracleAttestation)(nil), "terp.hashmerchant.v1.OracleAttestation")
	proto.RegisterType((*RegisteredContract)(nil), "terp.hashmerchant.v1.RegisteredContract")
	proto.RegisterType((*EscrowRecord)(nil), "terp.hashmerchant.v1.EscrowRecord")
	proto.RegisterType((*HashRoot)(nil), "terp.hashmerchant.v1.HashRoot")
	proto.RegisterType((*HashPairTicket)(nil), "terp.hashmerchant.v1.HashPairTicket")
	proto.RegisterType((*VoteExtensionHashData)(nil), "terp.hashmerchant.v1.VoteExtensionHashData")
}

func init() { proto.RegisterFile("terp/hashmerchant/v1/types.proto", fileDescriptor_fe086f74134e6aac) }

var fileDescriptor_fe086f74134e6aac = []byte{
	// 1211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x36, 0x25, 0xfa, 0x47, 0xc7, 0x94, 0x43, 0x0f, 0x74, 0x73, 0x95, 0x3f, 0x45, 0x57, 0xc1,
	0x6d, 0x55, 0xb7, 0x95, 0x6a, 0x07, 0x45, 0x8b, 0xee, 0x64, 0x5a, 0xad, 0x05, 0xc7, 0x96, 0x30,
	0x92, 0x5b, 0x20, 0x1b, 0x62, 0x44, 0x4e, 0xa4, 0xa9, 0x24, 0x0e, 0x31, 0x1c, 0x3a, 0x76, 0x56,
	0x7d, 0x84, 0x2c, 0xda, 0xd7, 0xe9, 0xaa, 0x8b, 0xa0, 0xab, 0x2c, 0xdb, 0x4d, 0x51, 0x24, 0xcb,
	0xbe, 0x44, 0x31, 0x43, 0xca, 0xa6, 0x1c, 0x25, 0x29, 0xd0, 0xdd, 0xcc, 0x77, 0x3e, 0x9d, 0x39,
	0x3f, 0xdf, 0x39, 0x22, 0x54, 0x25, 0x15, 0x61, 0x73, 0x4c, 0xa2, 0xf1, 0x8c, 0x0a, 0x6f, 0x4c,
	0x02, 0xd9, 0x3c, 0xdb, 0x6d, 0xca, 0x8b, 0x90, 0x46, 0x8d, 0x50, 0x70, 0xc9, 0x51, 0x49, 0x31,
	0x1a, 0x59, 0x46, 0xe3, 0x6c, 0xf7, 0x76, 0x69, 0xc4, 0x47, 0x5c, 0x13, 0x9a, 0xea, 0x94, 0x70,
	0x6f, 0x57, 0x3c, 0x1e, 0xcd, 0x78, 0xd4, 0x1c, 0x92, 0x88, 0x36, 0xcf, 0x76, 0x87, 0x54, 0x92,
	0xdd, 0xa6, 0xc7, 0x59, 0x90, 0xd8, 0x6b, 0x43, 0x28, 0x39, 0x71, 0x24, 0xb9, 0x7f, 0xd1, 0x8a,
	0xe5, 0x98, 0x06, 0x92, 0x79, 0x44, 0x72, 0x81, 0x6e, 0xc2, 0x5a, 0x18, 0x0f, 0x27, 0xf4, 0xa2,
	0x6c, 0x54, 0x8d, 0xba, 0x85, 0xd3, 0x1b, 0xba, 0x0b, 0x05, 0x32, 0x1d, 0x71, 0xc1, 0xe4, 0x78,
	0x56, 0xce, 0x55, 0x8d, 0x7a, 0x01, 0x5f, 0x01, 0xa8, 0x04, 0xab, 0x91, 0xc7, 0x43, 0x5a, 0xce,
	0x6b, 0x4b, 0x72, 0xa9, 0xfd, 0x98, 0x03, 0xab, 0x2b, 0x88, 0x37, 0xa5, 0x7d, 0x1e, 0x0b, 0x8f,
	0xa2, 0x3b, 0x50, 0x88, 0xf4, 0xc9, 0x65, 0xbe, 0xf6, 0x5f, 0xc0, 0x1b, 0x09, 0xd0, 0xf1, 0xd1,
	0x57, 0x60, 0x4e, 0x58, 0xe0, 0x6b, 0xe7, 0x5b, 0x7b, 0x1f, 0x34, 0x96, 0x25, 0xdb, 0xc8, 0xba,
	0x3b, 0x62, 0x81, 0x8f, 0xf5, 0x6f, 0xd0, 0x6d, 0xd8, 0xa0, 0x81, 0x1f, 0x72, 0x16, 0xc8, 0x34,
	0x84, 0xcb, 0x3b, 0x7a, 0x00, 0xc5, 0x19, 0x15, 0x93, 0x29, 0x75, 0x43, 0x41, 0x9f, 0xb0, 0xf3,
	0xb2, 0x59, 0xcd, 0xd7, 0x2d, 0x6c, 0x25, 0x60, 0x4f, 0x63, 0xa8, 0x07, 0x45, 0x92, 0xad, 0x43,
	0x79, 0xb5, 0x6a, 0xd4, 0x37, 0xf7, 0x76, 0x96, 0x47, 0xb1, 0xac, 0x72, 0x78, 0xd1, 0x01, 0x2a,
	0xc3, 0x3a, 0x0d, 0xc8, 0x70, 0x4a, 0xfd, 0xf2, 0x5a, 0xd5, 0xa8, 0x6f, 0xe0, 0xf9, 0xb5, 0xf6,
	0x97, 0x01, 0x37, 0x30, 0x1d, 0xb1, 0x48, 0x52, 0x41, 0x7d, 0x67, 0x4c, 0x58, 0xa0, 0x2a, 0xe3,
	0xa9, 0x83, 0x1b, 0x5f, 0x55, 0x46, 0x03, 0xa7, 0xcc, 0x47, 0x08, 0xcc, 0x80, 0xcc, 0x68, 0x5a,
	0x76, 0x7d, 0x56, 0x59, 0x89, 0xd0, 0x73, 0xe7, 0x59, 0x46, 0xe5, 0x7c, 0x35, 0x5f, 0x2f, 0x60,
	0x4b, 0x84, 0x5e, 0x7b, 0x8e, 0xa1, 0x7b, 0x00, 0x2a, 0x74, 0x57, 0x35, 0x2a, 0xd2, 0x79, 0x17,
	0x70, 0x41, 0x21, 0x2d, 0x05, 0x64, 0x43, 0x5c, 0x5d, 0x08, 0x11, 0x75, 0x60, 0x8b, 0xeb, 0x4a,
	0xbb, 0x49, 0x7b, 0xa2, 0xf2, 0x5a, 0x35, 0x5f, 0xdf, 0xdc, 0xab, 0xbd, 0xbf, 0x2b, 0xb8, 0xc8,
	0x33, 0xb7, 0xa8, 0xf6, 0xab, 0x01, 0xdb, 0x89, 0xbd, 0x25, 0x25, 0x8d, 0x24, 0x91, 0x8c, 0x07,
	0xef, 0x56, 0x42, 0x09, 0x56, 0xcf, 0xc8, 0x34, 0x4e, 0x12, 0xb6, 0x70, 0x72, 0x51, 0xca, 0x1c,
	0x53, 0x36, 0x1a, 0x27, 0x1d, 0x36, 0x71, 0x7a, 0x53, 0xca, 0x94, 0x6c, 0xa6, 0x3c, 0xcf, 0xc2,
	0xb2, 0x59, 0x35, 0xea, 0x79, 0x7c, 0x05, 0xa0, 0x8f, 0x61, 0xdb, 0x4b, 0xba, 0xe5, 0x46, 0x6c,
	0x14, 0x10, 0x19, 0x0b, 0xaa, 0xb3, 0xb5, 0xb0, 0x9d, 0x1a, 0xfa, 0x73, 0x1c, 0xdd, 0x87, 0x4d,
	0xe6, 0x45, 0x7b, 0x0f, 0xdd, 0x50, 0x70, 0xfe, 0x44, 0xf7, 0xcd, 0xc2, 0xa0, 0xa1, 0x9e, 0x42,
	0x6a, 0x3f, 0x19, 0x80, 0x32, 0xad, 0xe3, 0x81, 0x14, 0xc4, 0xd3, 0x12, 0xf3, 0xd2, 0xb3, 0x4b,
	0x7c, 0x5f, 0xa4, 0x19, 0x59, 0x73, 0xb0, 0xe5, 0xfb, 0x62, 0xb1, 0xc5, 0xb9, 0x6b, 0x2d, 0x7e,
	0x00, 0xc5, 0x28, 0x1e, 0x46, 0x92, 0x0b, 0xea, 0x4e, 0xe8, 0xc5, 0x65, 0x3b, 0xe7, 0xe0, 0x11,
	0xbd, 0x58, 0xe8, 0x97, 0xb9, 0x28, 0xa9, 0x5f, 0x0c, 0xb0, 0xda, 0x91, 0x27, 0xf8, 0x53, 0x4c,
	0x3d, 0x2e, 0xfc, 0x7f, 0x16, 0xd1, 0x17, 0xb0, 0x46, 0x66, 0x3c, 0x0e, 0xa4, 0x0e, 0x67, 0x73,
	0xef, 0x56, 0x23, 0x59, 0x1a, 0x0d, 0xb5, 0x34, 0x1a, 0xe9, 0xd2, 0x68, 0x38, 0x9c, 0x05, 0xfb,
	0xe6, 0x8b, 0x3f, 0xee, 0xaf, 0xe0, 0x94, 0x8e, 0x76, 0x60, 0x3b, 0x24, 0xcc, 0x77, 0xe3, 0x40,
	0xb2, 0xa9, 0xbb, 0xd0, 0x95, 0x1b, 0xca, 0x70, 0xaa, 0xf0, 0xc3, 0xa4, 0x3d, 0x3b, 0xb0, 0x3d,
	0x25, 0x91, 0x74, 0x43, 0x11, 0x07, 0x74, 0xce, 0x35, 0x13, 0xae, 0x32, 0xf4, 0x14, 0x9e, 0x70,
	0x6b, 0x3f, 0xe4, 0x60, 0xe3, 0x90, 0x44, 0x63, 0xcc, 0xb9, 0x7c, 0xef, 0x48, 0x28, 0x51, 0xcf,
	0x47, 0x42, 0x9d, 0xdf, 0x2a, 0x10, 0x04, 0xa6, 0xe0, 0x3c, 0x79, 0xd4, 0xc2, 0xfa, 0xac, 0x64,
	0x41, 0xae, 0xe4, 0xe8, 0x7a, 0xba, 0x0a, 0x4a, 0x16, 0x45, 0x6c, 0x67, 0x0c, 0x8e, 0x4e, 0xf7,
	0x1e, 0xc0, 0x70, 0xca, 0xbd, 0x89, 0xab, 0x64, 0xa5, 0x55, 0x91, 0xc7, 0x05, 0x8d, 0x0c, 0xd8,
	0x8c, 0xa2, 0x23, 0xb0, 0x32, 0x3f, 0x89, 0xca, 0xeb, 0x7a, 0x54, 0x3e, 0x7c, 0xd7, 0xa8, 0x64,
	0x46, 0x01, 0x2f, 0xfc, 0xb8, 0xf6, 0x3c, 0x07, 0x5b, 0xaa, 0x04, 0x3d, 0xc2, 0xc4, 0x80, 0x79,
	0x13, 0xaa, 0x9f, 0x0f, 0x05, 0xff, 0x9e, 0x7a, 0xf2, 0x6a, 0x58, 0x0a, 0x29, 0xd2, 0xf1, 0x95,
	0x68, 0xb9, 0x60, 0x23, 0x16, 0xb8, 0xea, 0xad, 0x74, 0x66, 0x20, 0x81, 0x94, 0x27, 0xf4, 0x11,
	0xd8, 0x3e, 0x8d, 0x24, 0x0b, 0x92, 0x5c, 0x35, 0x2b, 0xaf, 0x59, 0x37, 0x32, 0xb8, 0xa6, 0xd6,
	0xa0, 0xf8, 0x6c, 0xe2, 0x7a, 0x4c, 0x78, 0x31, 0xd3, 0xaf, 0x99, 0xfa, 0xb5, 0xcd, 0x67, 0x13,
	0x27, 0xc1, 0x3a, 0x3e, 0xfa, 0x0c, 0x4a, 0x59, 0x77, 0x49, 0x8f, 0x58, 0xb2, 0x42, 0x4c, 0x8c,
	0x32, 0x36, 0xbd, 0xda, 0x3a, 0x3e, 0xfa, 0x1f, 0x58, 0xf4, 0x3c, 0x64, 0xe2, 0xc2, 0xd5, 0x45,
	0xd3, 0x15, 0x34, 0xf1, 0x66, 0x82, 0xed, 0x2b, 0x48, 0x2d, 0xf0, 0x19, 0x95, 0xc4, 0x27, 0x92,
	0x94, 0xd7, 0x75, 0x6c, 0x97, 0xf7, 0xda, 0xcf, 0x39, 0xf8, 0xcf, 0xb7, 0x5c, 0xd2, 0xf6, 0xb9,
	0xa4, 0x41, 0x94, 0x86, 0x7a, 0x40, 0x24, 0x51, 0x95, 0x11, 0x4a, 0x83, 0xb3, 0xcc, 0x1a, 0x29,
	0xa4, 0x48, 0xc7, 0x7f, 0xf7, 0xc4, 0xcd, 0x15, 0x94, 0xcf, 0x28, 0x68, 0x99, 0x52, 0xfe, 0x0f,
	0x5b, 0x4f, 0xb8, 0xa0, 0x6c, 0x14, 0xcc, 0xc5, 0x9b, 0x24, 0x5a, 0x4c, 0xd1, 0x54, 0xe6, 0x9f,
	0x00, 0x9a, 0xd3, 0xde, 0xd0, 0x8a, 0x9d, 0x5a, 0xf6, 0x2f, 0x25, 0x73, 0x6d, 0xd1, 0xac, 0x5f,
	0x5f, 0x34, 0x6f, 0x68, 0x6a, 0xe3, 0x5f, 0x68, 0x6a, 0xe7, 0x3b, 0x80, 0x63, 0x22, 0x26, 0x54,
	0x1e, 0x73, 0x5f, 0xfd, 0x09, 0xff, 0xf7, 0xb8, 0x85, 0x8f, 0xda, 0x03, 0xf7, 0xb8, 0x7b, 0xd0,
	0x76, 0x4f, 0x4f, 0xfa, 0xbd, 0xb6, 0xd3, 0xf9, 0xba, 0xd3, 0x3e, 0xb0, 0x57, 0x50, 0x09, 0xec,
	0xac, 0xb1, 0xdb, 0x6b, 0x9f, 0xd8, 0x06, 0xba, 0x09, 0x28, 0x8b, 0x3a, 0x8f, 0xba, 0xfd, 0xf6,
	0x81, 0x9d, 0xdb, 0xf9, 0xdd, 0x00, 0xfb, 0xfa, 0x3f, 0x32, 0xaa, 0x41, 0xa5, 0x8b, 0x5b, 0xce,
	0xa3, 0xb6, 0xdb, 0xef, 0x9e, 0x62, 0xa7, 0xed, 0x1e, 0x75, 0x4e, 0x0e, 0xae, 0x3d, 0x73, 0x1f,
	0xee, 0x2c, 0xe1, 0xf4, 0xba, 0xfd, 0xc1, 0x37, 0xb8, 0xdd, 0xb7, 0x8d, 0xb7, 0x38, 0xd9, 0xef,
	0x0c, 0x9c, 0x6e, 0xe7, 0xc4, 0xc5, 0x3d, 0xc7, 0xce, 0xa1, 0x2a, 0xdc, 0x5d, 0xc2, 0x79, 0xec,
	0xb4, 0xfa, 0x87, 0x9a, 0x91, 0x57, 0xa9, 0x2e, 0x61, 0x1c, 0x0e, 0x06, 0x3d, 0xdb, 0x44, 0xf7,
	0xe0, 0xd6, 0x12, 0xa3, 0x73, 0xda, 0x1f, 0x74, 0x8f, 0xed, 0xd5, 0x7d, 0xfc, 0xe2, 0x55, 0xc5,
	0x78, 0xf9, 0xaa, 0x62, 0xfc, 0xf9, 0xaa, 0x62, 0x3c, 0x7f, 0x5d, 0x59, 0x79, 0xf9, 0xba, 0xb2,
	0xf2, 0xdb, 0xeb, 0xca, 0xca, 0xe3, 0x2f, 0x47, 0x4c, 0x8e, 0xe3, 0x61, 0xc3, 0xe3, 0xb3, 0xa6,
	0xea, 0x47, 0x40, 0xe5, 0x53, 0x2e, 0x26, 0xfa, 0xfc, 0xa9, 0xc7, 0x05, 0x6d, 0x9e, 0x7d, 0xde,
	0x3c, 0x5f, 0xfc, 0x92, 0xd3, 0x9f, 0x71, 0xc3, 0x35, 0xfd, 0xed, 0xf5, 0xf0, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x86, 0xfa, 0x0e, 0x64, 0xeb, 0x09, 0x00, 0x00,
}

func (m *CustodyAuthenticator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyAuthenticator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyAuthenticator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Scope) > 0 {
		i -= len(m.Scope)
		copy(dAtA[i:], m.Scope)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Scope)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Algorithm) > 0 {
		i -= len(m.Algorithm)
		copy(dAtA[i:], m.Algorithm)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Algorithm)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleSource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleSource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleSource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Authenticator != nil {
		{
			size, err := m.Authenticator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MerklePrefix) > 0 {
		for iNdEx := len(m.MerklePrefix) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MerklePrefix[iNdEx])
			copy(dAtA[i:], m.MerklePrefix[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.MerklePrefix[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Endpoint) > 0 {
		i -= len(m.Endpoint)
		copy(dAtA[i:], m.Endpoint)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Endpoint)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Kind != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SourceId) > 0 {
		i -= len(m.SourceId)
		copy(dAtA[i:], m.SourceId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisteredChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisteredChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisteredChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OracleSources) > 0 {
		for iNdEx := len(m.OracleSources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleSources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.HashAlgos) > 0 {
		for iNdEx := len(m.HashAlgos) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HashAlgos[iNdEx])
			copy(dAtA[i:], m.HashAlgos[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.HashAlgos[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RpcEndpoints) > 0 {
		for iNdEx := len(m.RpcEndpoints) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RpcEndpoints[iNdEx])
			copy(dAtA[i:], m.RpcEndpoints[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.RpcEndpoints[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleAttestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleAttestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleAttestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ics23Proof) > 0 {
		i -= len(m.Ics23Proof)
		copy(dAtA[i:], m.Ics23Proof)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Ics23Proof)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CustodySignature) > 0 {
		i -= len(m.CustodySignature)
		copy(dAtA[i:], m.CustodySignature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CustodySignature)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Timestamp != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourceId) > 0 {
		i -= len(m.SourceId)
		copy(dAtA[i:], m.SourceId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisteredContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisteredContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisteredContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.SubstoreKeys) > 0 {
		for iNdEx := len(m.SubstoreKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SubstoreKeys[iNdEx])
			copy(dAtA[i:], m.SubstoreKeys[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.SubstoreKeys[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EscrowRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EscrowRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EscrowRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastPruneHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.LastPruneHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.PaidUntilHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PaidUntilHeight))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HashRoot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashRoot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashRoot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.BlockTime != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockTime))
		i--
		dAtA[i] = 0x30
	}
	if m.AttestationCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AttestationCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x22
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Algo) > 0 {
		i -= len(m.Algo)
		copy(dAtA[i:], m.Algo)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Algo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HashPairTicket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashPairTicket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashPairTicket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ExpiryBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiryBlock))
		i--
		dAtA[i] = 0x30
	}
	if m.DestinationChainId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DestinationChainId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ZkCircuitId) > 0 {
		i -= len(m.ZkCircuitId)
		copy(dAtA[i:], m.ZkCircuitId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ZkCircuitId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DestinationHash) > 0 {
		i -= len(m.DestinationHash)
		copy(dAtA[i:], m.DestinationHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DestinationHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OriginHash) > 0 {
		i -= len(m.OriginHash)
		copy(dAtA[i:], m.OriginHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OriginHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProjectId) > 0 {
		i -= len(m.ProjectId)
		copy(dAtA[i:], m.ProjectId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProjectId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VoteExtensionHashData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteExtensionHashData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteExtensionHashData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Ics23Proof) > 0 {
		i -= len(m.Ics23Proof)
		copy(dAtA[i:], m.Ics23Proof)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Ics23Proof)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ForeignBlockTime != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ForeignBlockTime))
		i--
		dAtA[i] = 0x30
	}
	if m.ForeignHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ForeignHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Algo) > 0 {
		i -= len(m.Algo)
		copy(dAtA[i:], m.Algo)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Algo)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RuntimeId) > 0 {
		i -= len(m.RuntimeId)
		copy(dAtA[i:], m.RuntimeId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RuntimeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CustodyAuthenticator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Algorithm)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *OracleSource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovTypes(uint64(m.Kind))
	}
	l = len(m.Endpoint)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.MerklePrefix) > 0 {
		for _, b := range m.MerklePrefix {
			l = len(b)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Authenticator != nil {
		l = m.Authenticator.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *RegisteredChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.RpcEndpoints) > 0 {
		for _, s := range m.RpcEndpoints {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.HashAlgos) > 0 {
		for _, s := range m.HashAlgos {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Enabled {
		n += 2
	}
	if len(m.OracleSources) > 0 {
		for _, e := range m.OracleSources {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *OracleAttestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTypes(uint64(m.Timestamp))
	}
	l = len(m.CustodySignature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Ics23Proof)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *RegisteredContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.SubstoreKeys) > 0 {
		for _, s := range m.SubstoreKeys {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *EscrowRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.PaidUntilHeight != 0 {
		n += 1 + sovTypes(uint64(m.PaidUntilHeight))
	}
	if m.LastPruneHeight != 0 {
		n += 1 + sovTypes(uint64(m.LastPruneHeight))
	}
	return n
}

func (m *HashRoot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Algo)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AttestationCount != 0 {
		n += 1 + sovTypes(uint64(m.AttestationCount))
	}
	if m.BlockTime != 0 {
		n += 1 + sovTypes(uint64(m.BlockTime))
	}
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *HashPairTicket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProjectId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OriginHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DestinationHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ZkCircuitId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.DestinationChainId != 0 {
		n += 1 + sovTypes(uint64(m.DestinationChainId))
	}
	if m.ExpiryBlock != 0 {
		n += 1 + sovTypes(uint64(m.ExpiryBlock))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *VoteExtensionHashData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RuntimeId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Algo)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ForeignHeight != 0 {
		n += 1 + sovTypes(uint64(m.ForeignHeight))
	}
	if m.ForeignBlockTime != 0 {
		n += 1 + sovTypes(uint64(m.ForeignBlockTime))
	}
	l = len(m.Ics23Proof)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CustodyAuthenticator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyAuthenticator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyAuthenticator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = append(m.Pubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.Pubkey == nil {
				m.Pubkey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algorithm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Algorithm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleSource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleSource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleSource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= OracleSourceKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerklePrefix", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerklePrefix = append(m.MerklePrefix, make([]byte, postIndex-iNdEx))
			copy(m.MerklePrefix[len(m.MerklePrefix)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authenticator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Authenticator == nil {
				m.Authenticator = &CustodyAuthenticator{}
			}
			if err := m.Authenticator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisteredChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisteredChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisteredChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpcEndpoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpcEndpoints = append(m.RpcEndpoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashAlgos", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashAlgos = append(m.HashAlgos, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleSources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleSources = append(m.OracleSources, &OracleSource{})
			if err := m.OracleSources[len(m.OracleSources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleAttestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleAttestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleAttestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodySignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustodySignature = append(m.CustodySignature[:0], dAtA[iNdEx:postIndex]...)
			if m.CustodySignature == nil {
				m.CustodySignature = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ics23Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ics23Proof = append(m.Ics23Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Ics23Proof == nil {
				m.Ics23Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisteredContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisteredContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisteredContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubstoreKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubstoreKeys = append(m.SubstoreKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EscrowRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EscrowRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EscrowRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidUntilHeight", wireType)
			}
			m.PaidUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaidUntilHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPruneHeight", wireType)
			}
			m.LastPruneHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPruneHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashRoot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashRoot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashRoot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Algo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationCount", wireType)
			}
			m.AttestationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			m.BlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, &OracleAttestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashPairTicket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashPairTicket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashPairTicket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginHash = append(m.OriginHash[:0], dAtA[iNdEx:postIndex]...)
			if m.OriginHash == nil {
				m.OriginHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationHash = append(m.DestinationHash[:0], dAtA[iNdEx:postIndex]...)
			if m.DestinationHash == nil {
				m.DestinationHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkCircuitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkCircuitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationChainId", wireType)
			}
			m.DestinationChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryBlock", wireType)
			}
			m.ExpiryBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata[:0], dAtA[iNdEx:postIndex]...)
			if m.Metadata == nil {
				m.Metadata = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VoteExtensionHashData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteExtensionHashData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteExtensionHashData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuntimeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Algo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignHeight", wireType)
			}
			m.ForeignHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForeignHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignBlockTime", wireType)
			}
			m.ForeignBlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForeignBlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ics23Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ics23Proof = append(m.Ics23Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Ics23Proof == nil {
				m.Ics23Proof = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, &OracleAttestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
