// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terp/hashmerchant/v1/types.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MarketMode governs who may provide hash attestations.
type MarketMode int32

const (
	MarketMode_MARKET_MODE_UNSPECIFIED MarketMode = 0
	// Open: any validator may attest.
	MarketMode_MARKET_MODE_OPEN MarketMode = 1
	// Closed: only governance-whitelisted providers may attest.
	MarketMode_MARKET_MODE_CLOSED MarketMode = 2
)

var MarketMode_name = map[int32]string{
	0: "MARKET_MODE_UNSPECIFIED",
	1: "MARKET_MODE_OPEN",
	2: "MARKET_MODE_CLOSED",
}

var MarketMode_value = map[string]int32{
	"MARKET_MODE_UNSPECIFIED": 0,
	"MARKET_MODE_OPEN":        1,
	"MARKET_MODE_CLOSED":      2,
}

func (x MarketMode) String() string {
	return proto.EnumName(MarketMode_name, int32(x))
}

func (MarketMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{0}
}

// RegisteredChain describes a foreign blockchain whose substore roots
// validators will mirror via vote extensions.
type RegisteredChain struct {
	// chain_uid is the unique identifier (e.g. "cosmoshub-4", "ethereum-mainnet").
	ChainUid string `protobuf:"bytes,1,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	// human-readable label
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// rpc_endpoints that validator runtimes may query
	RpcEndpoints []string `protobuf:"bytes,3,rep,name=rpc_endpoints,json=rpcEndpoints,proto3" json:"rpc_endpoints,omitempty"`
	// hash_algos this chain supports (e.g. "sha256", "keccak256", "poseidon")
	HashAlgos []string `protobuf:"bytes,4,rep,name=hash_algos,json=hashAlgos,proto3" json:"hash_algos,omitempty"`
	// enabled toggles attestation acceptance
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *RegisteredChain) Reset()         { *m = RegisteredChain{} }
func (m *RegisteredChain) String() string { return proto.CompactTextString(m) }
func (*RegisteredChain) ProtoMessage()    {}
func (*RegisteredChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{0}
}
func (m *RegisteredChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisteredChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisteredChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisteredChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredChain.Merge(m, src)
}
func (m *RegisteredChain) XXX_Size() int {
	return m.Size()
}
func (m *RegisteredChain) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredChain.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredChain proto.InternalMessageInfo

func (m *RegisteredChain) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *RegisteredChain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisteredChain) GetRpcEndpoints() []string {
	if m != nil {
		return m.RpcEndpoints
	}
	return nil
}

func (m *RegisteredChain) GetHashAlgos() []string {
	if m != nil {
		return m.HashAlgos
	}
	return nil
}

func (m *RegisteredChain) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// RegisteredContract is a CosmWasm contract that has paid escrow to receive
// sudo callbacks when new hash roots are confirmed.
type RegisteredContract struct {
	ContractAddr string `protobuf:"bytes,1,opt,name=contract_addr,json=contractAddr,proto3" json:"contract_addr,omitempty"`
	ChainUid     string `protobuf:"bytes,2,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	// substore_keys the contract is interested in (e.g. ["bank", "staking"])
	SubstoreKeys []string `protobuf:"bytes,3,rep,name=substore_keys,json=substoreKeys,proto3" json:"substore_keys,omitempty"`
	Enabled      bool     `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *RegisteredContract) Reset()         { *m = RegisteredContract{} }
func (m *RegisteredContract) String() string { return proto.CompactTextString(m) }
func (*RegisteredContract) ProtoMessage()    {}
func (*RegisteredContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{1}
}
func (m *RegisteredContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisteredContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisteredContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisteredContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredContract.Merge(m, src)
}
func (m *RegisteredContract) XXX_Size() int {
	return m.Size()
}
func (m *RegisteredContract) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredContract.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredContract proto.InternalMessageInfo

func (m *RegisteredContract) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *RegisteredContract) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *RegisteredContract) GetSubstoreKeys() []string {
	if m != nil {
		return m.SubstoreKeys
	}
	return nil
}

func (m *RegisteredContract) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// EscrowRecord tracks the escrow deposit for a registered contract.
type EscrowRecord struct {
	ContractAddr string     `protobuf:"bytes,1,opt,name=contract_addr,json=contractAddr,proto3" json:"contract_addr,omitempty"`
	Amount       types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	// height through which the escrow is paid
	PaidUntilHeight uint64 `protobuf:"varint,3,opt,name=paid_until_height,json=paidUntilHeight,proto3" json:"paid_until_height,omitempty"`
	LastPruneHeight uint64 `protobuf:"varint,4,opt,name=last_prune_height,json=lastPruneHeight,proto3" json:"last_prune_height,omitempty"`
}

func (m *EscrowRecord) Reset()         { *m = EscrowRecord{} }
func (m *EscrowRecord) String() string { return proto.CompactTextString(m) }
func (*EscrowRecord) ProtoMessage()    {}
func (*EscrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{2}
}
func (m *EscrowRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EscrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EscrowRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EscrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowRecord.Merge(m, src)
}
func (m *EscrowRecord) XXX_Size() int {
	return m.Size()
}
func (m *EscrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowRecord proto.InternalMessageInfo

func (m *EscrowRecord) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *EscrowRecord) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EscrowRecord) GetPaidUntilHeight() uint64 {
	if m != nil {
		return m.PaidUntilHeight
	}
	return 0
}

func (m *EscrowRecord) GetLastPruneHeight() uint64 {
	if m != nil {
		return m.LastPruneHeight
	}
	return 0
}

// HashRoot is a confirmed foreign-chain state root stored on-chain after
// reaching validator quorum via vote extensions.
type HashRoot struct {
	ChainUid string `protobuf:"bytes,1,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	Algo     string `protobuf:"bytes,2,opt,name=algo,proto3" json:"algo,omitempty"`
	Height   uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Root     []byte `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	// number of validators that attested to this root
	AttestationCount uint32 `protobuf:"varint,5,opt,name=attestation_count,json=attestationCount,proto3" json:"attestation_count,omitempty"`
	// block_time of the foreign chain (unix seconds)
	BlockTime int64 `protobuf:"varint,6,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
}

func (m *HashRoot) Reset()         { *m = HashRoot{} }
func (m *HashRoot) String() string { return proto.CompactTextString(m) }
func (*HashRoot) ProtoMessage()    {}
func (*HashRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{3}
}
func (m *HashRoot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashRoot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRoot.Merge(m, src)
}
func (m *HashRoot) XXX_Size() int {
	return m.Size()
}
func (m *HashRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRoot.DiscardUnknown(m)
}

var xxx_messageInfo_HashRoot proto.InternalMessageInfo

func (m *HashRoot) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *HashRoot) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *HashRoot) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HashRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *HashRoot) GetAttestationCount() uint32 {
	if m != nil {
		return m.AttestationCount
	}
	return 0
}

func (m *HashRoot) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

// HashPairTicket is the core on-chain primitive: a filterable, zk-optimised
// pair of hashes linking an origin chain state to a destination representation.
type HashPairTicket struct {
	ProjectId          string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	OriginHash         []byte `protobuf:"bytes,2,opt,name=origin_hash,json=originHash,proto3" json:"origin_hash,omitempty"`
	DestinationHash    []byte `protobuf:"bytes,3,opt,name=destination_hash,json=destinationHash,proto3" json:"destination_hash,omitempty"`
	ZkCircuitId        string `protobuf:"bytes,4,opt,name=zk_circuit_id,json=zkCircuitId,proto3" json:"zk_circuit_id,omitempty"`
	DestinationChainId uint64 `protobuf:"varint,5,opt,name=destination_chain_id,json=destinationChainId,proto3" json:"destination_chain_id,omitempty"`
	ExpiryBlock        uint64 `protobuf:"varint,6,opt,name=expiry_block,json=expiryBlock,proto3" json:"expiry_block,omitempty"`
	Metadata           []byte `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *HashPairTicket) Reset()         { *m = HashPairTicket{} }
func (m *HashPairTicket) String() string { return proto.CompactTextString(m) }
func (*HashPairTicket) ProtoMessage()    {}
func (*HashPairTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{4}
}
func (m *HashPairTicket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashPairTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashPairTicket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashPairTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashPairTicket.Merge(m, src)
}
func (m *HashPairTicket) XXX_Size() int {
	return m.Size()
}
func (m *HashPairTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_HashPairTicket.DiscardUnknown(m)
}

var xxx_messageInfo_HashPairTicket proto.InternalMessageInfo

func (m *HashPairTicket) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *HashPairTicket) GetOriginHash() []byte {
	if m != nil {
		return m.OriginHash
	}
	return nil
}

func (m *HashPairTicket) GetDestinationHash() []byte {
	if m != nil {
		return m.DestinationHash
	}
	return nil
}

func (m *HashPairTicket) GetZkCircuitId() string {
	if m != nil {
		return m.ZkCircuitId
	}
	return ""
}

func (m *HashPairTicket) GetDestinationChainId() uint64 {
	if m != nil {
		return m.DestinationChainId
	}
	return 0
}

func (m *HashPairTicket) GetExpiryBlock() uint64 {
	if m != nil {
		return m.ExpiryBlock
	}
	return 0
}

func (m *HashPairTicket) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// VoteExtensionHashData is the payload validators include in their ABCI++
// vote extensions.  It bundles a hash-pair ticket with the ICS-23 proof
// material that the on-chain module uses for verification.
type VoteExtensionHashData struct {
	RuntimeId        string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ChainUid         string `protobuf:"bytes,2,opt,name=chain_uid,json=chainUid,proto3" json:"chain_uid,omitempty"`
	Algo             string `protobuf:"bytes,3,opt,name=algo,proto3" json:"algo,omitempty"`
	Root             []byte `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	ForeignHeight    uint64 `protobuf:"varint,5,opt,name=foreign_height,json=foreignHeight,proto3" json:"foreign_height,omitempty"`
	ForeignBlockTime int64  `protobuf:"varint,6,opt,name=foreign_block_time,json=foreignBlockTime,proto3" json:"foreign_block_time,omitempty"`
	// ics23_proof is an optional ICS-23 commitment proof for the root
	Ics23Proof []byte `protobuf:"bytes,7,opt,name=ics23_proof,json=ics23Proof,proto3" json:"ics23_proof,omitempty"`
}

func (m *VoteExtensionHashData) Reset()         { *m = VoteExtensionHashData{} }
func (m *VoteExtensionHashData) String() string { return proto.CompactTextString(m) }
func (*VoteExtensionHashData) ProtoMessage()    {}
func (*VoteExtensionHashData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe086f74134e6aac, []int{5}
}
func (m *VoteExtensionHashData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteExtensionHashData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteExtensionHashData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteExtensionHashData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteExtensionHashData.Merge(m, src)
}
func (m *VoteExtensionHashData) XXX_Size() int {
	return m.Size()
}
func (m *VoteExtensionHashData) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteExtensionHashData.DiscardUnknown(m)
}

var xxx_messageInfo_VoteExtensionHashData proto.InternalMessageInfo

func (m *VoteExtensionHashData) GetRuntimeId() string {
	if m != nil {
		return m.RuntimeId
	}
	return ""
}

func (m *VoteExtensionHashData) GetChainUid() string {
	if m != nil {
		return m.ChainUid
	}
	return ""
}

func (m *VoteExtensionHashData) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *VoteExtensionHashData) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *VoteExtensionHashData) GetForeignHeight() uint64 {
	if m != nil {
		return m.ForeignHeight
	}
	return 0
}

func (m *VoteExtensionHashData) GetForeignBlockTime() int64 {
	if m != nil {
		return m.ForeignBlockTime
	}
	return 0
}

func (m *VoteExtensionHashData) GetIcs23Proof() []byte {
	if m != nil {
		return m.Ics23Proof
	}
	return nil
}

func init() {
	proto.RegisterEnum("terp.hashmerchant.v1.MarketMode", MarketMode_name, MarketMode_value)
	proto.RegisterType((*RegisteredChain)(nil), "terp.hashmerchant.v1.RegisteredChain")
	proto.RegisterType((*RegisteredContract)(nil), "terp.hashmerchant.v1.RegisteredContract")
	proto.RegisterType((*EscrowRecord)(nil), "terp.hashmerchant.v1.EscrowRecord")
	proto.RegisterType((*HashRoot)(nil), "terp.hashmerchant.v1.HashRoot")
	proto.RegisterType((*HashPairTicket)(nil), "terp.hashmerchant.v1.HashPairTicket")
	proto.RegisterType((*VoteExtensionHashData)(nil), "terp.hashmerchant.v1.VoteExtensionHashData")
}

func init() { proto.RegisterFile("terp/hashmerchant/v1/types.proto", fileDescriptor_fe086f74134e6aac) }

var fileDescriptor_fe086f74134e6aac = []byte{
	// 834 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6e, 0x1b, 0x45,
	0x18, 0xc7, 0xbd, 0xf1, 0x92, 0xc6, 0x5f, 0xec, 0xc6, 0x1d, 0x85, 0xb2, 0xa4, 0xaa, 0x6b, 0x5c,
	0x21, 0x99, 0x02, 0x5e, 0xd2, 0x0a, 0xc1, 0x35, 0x71, 0x16, 0xd5, 0x2a, 0x69, 0xac, 0x6d, 0x02,
	0x12, 0x97, 0xd5, 0x78, 0x66, 0x6a, 0x0f, 0xf6, 0xce, 0xac, 0x66, 0xc6, 0x69, 0xdc, 0xa7, 0xe8,
	0x85, 0x3b, 0xef, 0xc0, 0x2b, 0x70, 0xe8, 0x31, 0x47, 0x4e, 0x08, 0x25, 0x4f, 0xc0, 0x1b, 0xa0,
	0x99, 0xdd, 0x8d, 0xd6, 0x80, 0xa0, 0xb7, 0x6f, 0x7e, 0xdf, 0xdf, 0x9e, 0xff, 0x37, 0xff, 0xd9,
	0x81, 0xae, 0x61, 0x2a, 0x0b, 0x67, 0x58, 0xcf, 0x52, 0xa6, 0xc8, 0x0c, 0x0b, 0x13, 0x9e, 0xef,
	0x87, 0x66, 0x95, 0x31, 0x3d, 0xc8, 0x94, 0x34, 0x12, 0xed, 0x5a, 0xc5, 0xa0, 0xaa, 0x18, 0x9c,
	0xef, 0xef, 0xed, 0x4e, 0xe5, 0x54, 0x3a, 0x41, 0x68, 0xab, 0x5c, 0xbb, 0xd7, 0x21, 0x52, 0xa7,
	0x52, 0x87, 0x13, 0xac, 0x59, 0x78, 0xbe, 0x3f, 0x61, 0x06, 0xef, 0x87, 0x44, 0x72, 0x91, 0xf7,
	0x7b, 0x3f, 0x7b, 0xb0, 0x13, 0xb3, 0x29, 0xd7, 0x86, 0x29, 0x46, 0x87, 0x33, 0xcc, 0x05, 0xba,
	0x07, 0x0d, 0x62, 0x8b, 0x64, 0xc9, 0x69, 0xe0, 0x75, 0xbd, 0x7e, 0x23, 0xde, 0x72, 0xe0, 0x8c,
	0x53, 0x84, 0xc0, 0x17, 0x38, 0x65, 0xc1, 0x86, 0xe3, 0xae, 0x46, 0x0f, 0xa1, 0xa5, 0x32, 0x92,
	0x30, 0x41, 0x33, 0xc9, 0x85, 0xd1, 0x41, 0xbd, 0x5b, 0xef, 0x37, 0xe2, 0xa6, 0xca, 0x48, 0x54,
	0x32, 0x74, 0x1f, 0xc0, 0x5a, 0x4e, 0xf0, 0x62, 0x2a, 0x75, 0xe0, 0x3b, 0x45, 0xc3, 0x92, 0x03,
	0x0b, 0x50, 0x00, 0xb7, 0x98, 0xc0, 0x93, 0x05, 0xa3, 0xc1, 0x7b, 0x5d, 0xaf, 0xbf, 0x15, 0x97,
	0xcb, 0xde, 0x4f, 0x1e, 0xa0, 0x8a, 0x45, 0x29, 0x8c, 0xc2, 0xc4, 0xd8, 0x4d, 0x49, 0x51, 0x27,
	0x98, 0x52, 0x55, 0x38, 0x6d, 0x96, 0xf0, 0x80, 0x52, 0xb5, 0x3e, 0xca, 0xc6, 0xdf, 0x46, 0x79,
	0x08, 0x2d, 0xbd, 0x9c, 0x68, 0x23, 0x15, 0x4b, 0xe6, 0x6c, 0x75, 0x63, 0xbb, 0x84, 0xcf, 0xd8,
	0x6a, 0xcd, 0x97, 0xbf, 0xee, 0xeb, 0x57, 0x0f, 0x9a, 0x91, 0x26, 0x4a, 0xbe, 0x8a, 0x19, 0x91,
	0x8a, 0xbe, 0x9b, 0xa3, 0xaf, 0x60, 0x13, 0xa7, 0x72, 0x29, 0x8c, 0xb3, 0xb3, 0xfd, 0xf8, 0xc3,
	0x41, 0x9e, 0xd0, 0xc0, 0x26, 0x34, 0x28, 0x12, 0x1a, 0x0c, 0x25, 0x17, 0x87, 0xfe, 0xdb, 0xdf,
	0x1f, 0xd4, 0xe2, 0x42, 0x8e, 0x1e, 0xc1, 0x9d, 0x0c, 0x73, 0x9a, 0x2c, 0x85, 0xe1, 0x8b, 0x64,
	0xc6, 0xf8, 0x74, 0x66, 0x82, 0x7a, 0xd7, 0xeb, 0xfb, 0xf1, 0x8e, 0x6d, 0x9c, 0x59, 0xfe, 0xd4,
	0x61, 0xab, 0x5d, 0x60, 0x6d, 0x92, 0x4c, 0x2d, 0x05, 0x2b, 0xb5, 0x7e, 0xae, 0xb5, 0x8d, 0xb1,
	0xe5, 0xb9, 0xb6, 0xf7, 0x8b, 0x07, 0x5b, 0x4f, 0xb1, 0x9e, 0xc5, 0x52, 0x9a, 0xff, 0x8d, 0xde,
	0x86, 0x57, 0x46, 0x6f, 0x6b, 0x74, 0x17, 0x36, 0xd7, 0xac, 0x14, 0x2b, 0xab, 0x55, 0x52, 0xe6,
	0x9b, 0x36, 0x63, 0x57, 0xa3, 0x4f, 0xe1, 0x0e, 0x36, 0x86, 0x69, 0x83, 0x0d, 0x97, 0x22, 0x21,
	0xee, 0x14, 0x6c, 0xd8, 0xad, 0xb8, 0x5d, 0x69, 0x0c, 0xdd, 0xb8, 0xf7, 0x01, 0x26, 0x0b, 0x49,
	0xe6, 0x89, 0xe1, 0x29, 0x0b, 0x36, 0xbb, 0x5e, 0xbf, 0x1e, 0x37, 0x1c, 0x39, 0xe5, 0x29, 0xeb,
	0xbd, 0xd9, 0x80, 0xdb, 0xd6, 0xf5, 0x18, 0x73, 0x75, 0xca, 0xc9, 0x9c, 0xb9, 0x5f, 0x64, 0x4a,
	0xfe, 0xc8, 0x88, 0x49, 0x6e, 0xcc, 0x37, 0x0a, 0x32, 0xa2, 0xe8, 0x01, 0x6c, 0x4b, 0xc5, 0xa7,
	0x5c, 0x24, 0xf6, 0xd2, 0xb9, 0x21, 0x9a, 0x31, 0xe4, 0xc8, 0xfe, 0x13, 0xfa, 0x04, 0xda, 0x94,
	0x69, 0xc3, 0x45, 0x6e, 0xcf, 0xa9, 0xea, 0x4e, 0xb5, 0x53, 0xe1, 0x4e, 0xda, 0x83, 0xd6, 0xeb,
	0x79, 0x42, 0xb8, 0x22, 0x4b, 0xee, 0x76, 0xf3, 0xdd, 0x6e, 0xdb, 0xaf, 0xe7, 0xc3, 0x9c, 0x8d,
	0x28, 0xfa, 0x02, 0x76, 0xab, 0x7f, 0x97, 0x1f, 0x2b, 0xcf, 0x6f, 0xb7, 0x1f, 0xa3, 0x4a, 0xcf,
	0x7d, 0x75, 0x23, 0x8a, 0x3e, 0x82, 0x26, 0xbb, 0xc8, 0xb8, 0x5a, 0x25, 0x6e, 0x4e, 0x37, 0xb4,
	0x1f, 0x6f, 0xe7, 0xec, 0xd0, 0x22, 0xb4, 0x07, 0x5b, 0x29, 0x33, 0x98, 0x62, 0x83, 0x83, 0x5b,
	0xce, 0xdb, 0xcd, 0xba, 0xf7, 0xa7, 0x07, 0xef, 0x7f, 0x27, 0x0d, 0x8b, 0x2e, 0x0c, 0x13, 0xba,
	0xb0, 0x7a, 0x84, 0x0d, 0xb6, 0x27, 0xa3, 0xec, 0xb5, 0x49, 0x59, 0xe5, 0x64, 0x0a, 0x32, 0xa2,
	0xff, 0xfd, 0x91, 0x94, 0xa1, 0xd7, 0x2b, 0xa1, 0xff, 0x5b, 0xb8, 0x1f, 0xc3, 0xed, 0x97, 0x52,
	0x31, 0x3e, 0x15, 0xe5, 0x7d, 0xcb, 0x07, 0x6d, 0x15, 0xb4, 0xb8, 0x99, 0x9f, 0x01, 0x2a, 0x65,
	0xff, 0x88, 0xb7, 0x5d, 0x74, 0x0e, 0xcb, 0x94, 0x6d, 0x66, 0x9c, 0xe8, 0xc7, 0x4f, 0x92, 0x4c,
	0x49, 0xf9, 0xb2, 0x98, 0x18, 0x1c, 0x1a, 0x5b, 0xf2, 0xe8, 0x7b, 0x80, 0x63, 0xac, 0xe6, 0xcc,
	0x1c, 0x4b, 0xca, 0xd0, 0x3d, 0xf8, 0xe0, 0xf8, 0x20, 0x7e, 0x16, 0x9d, 0x26, 0xc7, 0x27, 0x47,
	0x51, 0x72, 0xf6, 0xfc, 0xc5, 0x38, 0x1a, 0x8e, 0xbe, 0x19, 0x45, 0x47, 0xed, 0x1a, 0xda, 0x85,
	0x76, 0xb5, 0x79, 0x32, 0x8e, 0x9e, 0xb7, 0x3d, 0x74, 0x17, 0x50, 0x95, 0x0e, 0xbf, 0x3d, 0x79,
	0x11, 0x1d, 0xb5, 0x37, 0x0e, 0xe3, 0xb7, 0x57, 0x1d, 0xef, 0xf2, 0xaa, 0xe3, 0xfd, 0x71, 0xd5,
	0xf1, 0xde, 0x5c, 0x77, 0x6a, 0x97, 0xd7, 0x9d, 0xda, 0x6f, 0xd7, 0x9d, 0xda, 0x0f, 0x5f, 0x4f,
	0xb9, 0x99, 0x2d, 0x27, 0x03, 0x22, 0xd3, 0xd0, 0x3e, 0xc4, 0x82, 0x99, 0x57, 0x52, 0xcd, 0x5d,
	0xfd, 0x39, 0x91, 0x8a, 0x85, 0xe7, 0x5f, 0x86, 0x17, 0xeb, 0x0f, 0xb8, 0x7b, 0xbd, 0x27, 0x9b,
	0xee, 0xc9, 0x7d, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xdb, 0x1d, 0xbe, 0xe2, 0x05,
	0x00, 0x00,
}

func (m *RegisteredChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisteredChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisteredChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.HashAlgos) > 0 {
		for iNdEx := len(m.HashAlgos) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HashAlgos[iNdEx])
			copy(dAtA[i:], m.HashAlgos[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.HashAlgos[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RpcEndpoints) > 0 {
		for iNdEx := len(m.RpcEndpoints) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RpcEndpoints[iNdEx])
			copy(dAtA[i:], m.RpcEndpoints[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.RpcEndpoints[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisteredContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisteredContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisteredContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.SubstoreKeys) > 0 {
		for iNdEx := len(m.SubstoreKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SubstoreKeys[iNdEx])
			copy(dAtA[i:], m.SubstoreKeys[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.SubstoreKeys[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EscrowRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EscrowRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EscrowRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastPruneHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.LastPruneHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.PaidUntilHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PaidUntilHeight))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HashRoot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashRoot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashRoot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockTime != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockTime))
		i--
		dAtA[i] = 0x30
	}
	if m.AttestationCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AttestationCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x22
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Algo) > 0 {
		i -= len(m.Algo)
		copy(dAtA[i:], m.Algo)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Algo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HashPairTicket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashPairTicket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashPairTicket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ExpiryBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiryBlock))
		i--
		dAtA[i] = 0x30
	}
	if m.DestinationChainId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DestinationChainId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ZkCircuitId) > 0 {
		i -= len(m.ZkCircuitId)
		copy(dAtA[i:], m.ZkCircuitId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ZkCircuitId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DestinationHash) > 0 {
		i -= len(m.DestinationHash)
		copy(dAtA[i:], m.DestinationHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DestinationHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OriginHash) > 0 {
		i -= len(m.OriginHash)
		copy(dAtA[i:], m.OriginHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OriginHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProjectId) > 0 {
		i -= len(m.ProjectId)
		copy(dAtA[i:], m.ProjectId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProjectId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VoteExtensionHashData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteExtensionHashData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteExtensionHashData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ics23Proof) > 0 {
		i -= len(m.Ics23Proof)
		copy(dAtA[i:], m.Ics23Proof)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Ics23Proof)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ForeignBlockTime != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ForeignBlockTime))
		i--
		dAtA[i] = 0x30
	}
	if m.ForeignHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ForeignHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Algo) > 0 {
		i -= len(m.Algo)
		copy(dAtA[i:], m.Algo)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Algo)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainUid) > 0 {
		i -= len(m.ChainUid)
		copy(dAtA[i:], m.ChainUid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainUid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RuntimeId) > 0 {
		i -= len(m.RuntimeId)
		copy(dAtA[i:], m.RuntimeId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RuntimeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RegisteredChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.RpcEndpoints) > 0 {
		for _, s := range m.RpcEndpoints {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.HashAlgos) > 0 {
		for _, s := range m.HashAlgos {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *RegisteredContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.SubstoreKeys) > 0 {
		for _, s := range m.SubstoreKeys {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *EscrowRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.PaidUntilHeight != 0 {
		n += 1 + sovTypes(uint64(m.PaidUntilHeight))
	}
	if m.LastPruneHeight != 0 {
		n += 1 + sovTypes(uint64(m.LastPruneHeight))
	}
	return n
}

func (m *HashRoot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Algo)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AttestationCount != 0 {
		n += 1 + sovTypes(uint64(m.AttestationCount))
	}
	if m.BlockTime != 0 {
		n += 1 + sovTypes(uint64(m.BlockTime))
	}
	return n
}

func (m *HashPairTicket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProjectId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OriginHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DestinationHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ZkCircuitId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.DestinationChainId != 0 {
		n += 1 + sovTypes(uint64(m.DestinationChainId))
	}
	if m.ExpiryBlock != 0 {
		n += 1 + sovTypes(uint64(m.ExpiryBlock))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *VoteExtensionHashData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RuntimeId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChainUid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Algo)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ForeignHeight != 0 {
		n += 1 + sovTypes(uint64(m.ForeignHeight))
	}
	if m.ForeignBlockTime != 0 {
		n += 1 + sovTypes(uint64(m.ForeignBlockTime))
	}
	l = len(m.Ics23Proof)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegisteredChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisteredChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisteredChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpcEndpoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpcEndpoints = append(m.RpcEndpoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashAlgos", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashAlgos = append(m.HashAlgos, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisteredContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisteredContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisteredContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubstoreKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubstoreKeys = append(m.SubstoreKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EscrowRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EscrowRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EscrowRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidUntilHeight", wireType)
			}
			m.PaidUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaidUntilHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPruneHeight", wireType)
			}
			m.LastPruneHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPruneHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashRoot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashRoot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashRoot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Algo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationCount", wireType)
			}
			m.AttestationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			m.BlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashPairTicket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashPairTicket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashPairTicket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginHash = append(m.OriginHash[:0], dAtA[iNdEx:postIndex]...)
			if m.OriginHash == nil {
				m.OriginHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationHash = append(m.DestinationHash[:0], dAtA[iNdEx:postIndex]...)
			if m.DestinationHash == nil {
				m.DestinationHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkCircuitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkCircuitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationChainId", wireType)
			}
			m.DestinationChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryBlock", wireType)
			}
			m.ExpiryBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata[:0], dAtA[iNdEx:postIndex]...)
			if m.Metadata == nil {
				m.Metadata = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VoteExtensionHashData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteExtensionHashData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteExtensionHashData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuntimeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Algo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignHeight", wireType)
			}
			m.ForeignHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForeignHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignBlockTime", wireType)
			}
			m.ForeignBlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForeignBlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ics23Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ics23Proof = append(m.Ics23Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Ics23Proof == nil {
				m.Ics23Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
